name: Actualizar datos financieros

on:
  schedule:
    - cron: '0 16 * * *'  # Ejecuta a las 16:00 UTC todos los días
  workflow_dispatch:

jobs:
  update-stock:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: |
        pip install yfinance pandas

    - name: Ejecutar script de actualización
      run: python Actual_Stock.py

    - name: Commit y push cambios
      uses: EndBug/add-and-commit@v9
      with:
        message: "📈 Actualización diaria automática"
        add: "Actual_Stock.csv"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
