name: Actualizar datos financieros

on:
  schedule:
    - cron: '0 16 * * *'  # Ejecuta a las 16:00 UTC todos los días
  workflow_dispatch:

jobs:
  update-stock:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install yfinance pandas

    - name: Ejecutar script Actual_Stock.py
      run: python Actual_Stock.py

    - name: Commit y push cambios
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "📈 Actualización diaria automática"
        file_pattern: "Actual_Stock.csv"
        branch: main
        commit_user_name: "github-actions"
        commit_user_email: "github-actions@github.com"
        token: ${{ secrets.GITHUB_TOKEN }}
